### ISSUE TITLE
Agile Story #3 (Member Class)

### ISSUE THREAD

**Issue by ghost** [ywang208/cs-8-first-project#27]
---
# Agile Story #3 (Member Class)
---

## WHAT NEEDS TO BE DONE (User Story):
**`“As a programmer, I want to build a MembersList class to read in data from a text file and vice versa, be able to update new data about the members purchases and any changes made to edit they membership status. This class will deal with both the members options and members reports. As we discussed previously in our design stage, we decided to create a struct within the class to store the members info such as name, id, date, type, rebate amount for preferred only, and the amount total spent. In the Member struct, we created a constructor with name, id, type, date, rebate
and spend. Now, in the MembersList class, we have created a default constructor along with a constructor with the file name to get the data from the file and vice versa (to update). In here, we created an operator "=" to copy other constructors. We also created operators "[]" to show the position of the members information as needed. We also decided that we needed to create functions to add and delete members called "addMembers" and "deleteMember".  Lastly, we decided to add functions to display the members reports.`**

---
> - Story Point Estimation: 4
> - Story Point Priority: Medium-Low
> - Assignee: @phildkim86
> - Task 1: ~~Create a class to read in data from text file.~~
> - Task 2: ~~Create a class to read out data from text file.~~
> - Task 3: ~~Create a class to display reports.~~
---

## PROBLEMS:
`I ran into a lot problem with this function as I was developing because initially I was only considering basic members and forgot to implement for preferred.`

```c++
bool MembersList::isExist(int id, string name)
```

## SUGGESTIONS:
` @ywang208 👍  : I suggest you add if, else if to check for id and name size. First if, should check both id and name size, then do the next else if to check for id is negative, and lastly check to see if name size is 0, otherwise return false.`

### Definition of Done 
- [x] ~~Code produced that adheres to a coding standard Code commented~~
- [x] ~~Code checked into source control system~~
- [x] ~~Peer reviewed (or produced with pair programming) Unit tests written and passed~~
- [x] ~~Relevant documentation/diagrams produced and/or updated Product owner concurs~~
> Peer reviewed by: @ywang208 & @dthai5 

> ### Developer said,
`"How I tested the coded: I tested the code by reading the warehouseshoppers.txt and along with all of the days.txt and made sure that i was reading read data correctly and made sure that all the data was in the correct position. This testing was pretty simple because you can see the result right away and everything came out smooth. On the other hand, although reading out the data to another text file was pretty much the same thing as reading in but we had to make sure we update the proper member info such was kind of tricky but after doing a lot of testing but adding new purchases the members made, I was finally able to output the result on the proper text file."`
